### ISSUE TITLE
My Profile Page doesn't show posts

### ISSUE THREAD

**Issue by Sudipta638** [adrianhajdin/project_next_13_ai_prompt_sharing#10]
My profile page does not show any posts 
![git1](https://github.com/adrianhajdin/project_next_13_ai_prompt_sharing/assets/124155704/96dae15a-13cd-497b-9079-f9339f612fa2)
![Screenshot (368)](https://github.com/adrianhajdin/project_next_13_ai_prompt_sharing/assets/124155704/5c3da006-f6e5-48a2-919f-87012bff2e57)

![git2](https://github.com/adrianhajdin/project_next_13_ai_prompt_sharing/assets/124155704/8a04968e-e022-4a67-9c17-e780b6a41f9e)

**Comment by davidcastagnetoa** [comment]
@Sudipta638 : try to remove _session?.user?.id_  from the useEffect in the array, in your last line. Something like this: 

```
  useEffect(() => {
    const fetchPosts = async () => {
      const response = await fetch(`/api/users/${session?.user?.id}/posts`);
      const data = await response.json();

      // Sort posts by date
      setMyPosts(data);
    };
    console.log(myPosts);
    // Only fetch posts if user is authenticated
    if (session?.user?.id) fetchPosts();
  }, []);
```

The last line is an void array. Good luck

**Comment by Sudipta638** [comment]
@davidcastagnetoa  thanks for your concern. But the issue has not gone y
![Screenshot (369)](https://github.com/adrianhajdin/project_next_13_ai_prompt_sharing/assets/124155704/97a6d138-7a49-47c6-a02f-038b0ec8da0c)
et.

**Comment by Sudipta638** [comment]
It solved .It will be "
      const response = await fetch(`/api/user/${session?.user?.id}/posts`);"
