### ISSUE TITLE
Errors thrown by next.js which work in youtube course

### ISSUE THREAD

**Issue by kikky7** [adrianhajdin/project_next_13_ai_prompt_sharing#26]
I am learning Next.js and I am currently at the beginning of prompt creation.

I code along the video and I ran in few issues (I don't know if anyone else did since I don't see those issues mentioned here or in youtube comments).

1. Fetching image from Google threw me an error that hostname is not configured: I fixed it with remotePatterns which I found in Next.js docs. However, now I see in source code that you also set this in next.config.js (using domain, not patterns), but it was never mentioned in video (or maybe I skipped it).
2. Getting user from database inside session callback throws me mongodb timeout error (buffering timed out after 10000ms), so I was required to add this line of code `await connectToDB();` at the start of callbacks async session function (nextauth route.js). This happens when I login with google account, then stop the app and then start it again with `npm run dev`. Session still outputs my google account data, but `User.findOne()` fails since it can't connect to database. Is this line required if this was app for production?

**Comment by gr8guyrabi** [comment]
Everything seems to work for me!!! would it be possible to share your code?
