### ISSUE TITLE
Navbar user profile not displaying

### ISSUE THREAD

**Issue by billy3b** [adrianhajdin/project_next_13_ai_prompt_sharing#34]
![image](https://github.com/adrianhajdin/project_next_13_ai_prompt_sharing/assets/108816279/bd90c5d8-73aa-404c-a1bb-23d6af40fcba)

![image](https://github.com/adrianhajdin/project_next_13_ai_prompt_sharing/assets/108816279/01f320e1-af67-4c3d-88bb-2871a3b5b03c)

**Comment by ablaackcat** [comment]
Hello!

I've noticed you have a typo in your code.
key={provider**s**.name} is without the **s**
as well as at:
signIn(provider.**I**d) - Don't capitalize it

![ProblemSolved](https://github.com/adrianhajdin/project_next_13_ai_prompt_sharing/assets/121575236/cc268cca-f40f-4859-a4f0-22b0740c8fae)

**Comment by billy3b** [comment]
Issue resolved
