### ISSUE TITLE
HomePage Feed not updating in deployed version

### ISSUE THREAD

**Issue by sumanth-botlagunta** [adrianhajdin/project_next_13_ai_prompt_sharing#35]
@adrianhajdin
Hi there,  
In **deployed version** when I create or edit a post the profile page Feed section is updated with the new post data but **home page Feed section is not updated**. I tried a lot I was not able to get it it done.

my code: https://github.com/sumanth-botlagunta/AI-prompt-sharing-web-app/tree/master
my website: https://ai-prompt-sharing-web-app.vercel.app/

Someone help me out with this
**Thanks in advance**

**Comment by osman-sultan** [comment]
same issue, local host gets updated but not deployed version

**Comment by andreshungbz** [comment]
I've been having the same issue but I managed to get it to work somehow, though I won't be able to why exactly it works since I'm in the same boat of just learning how to use Next.js through this tutorial (so if someone would be able to do that or improve/explain the code below I'd greatly appreciate it!).

I edited the `/app/api/prompt/route.js` to be this:
```
import Prompt from '@models/prompt';
import { connectToDB } from '@utils/database';
import { headers } from 'next/headers';

export const GET = async (request) => {
  const headersList = headers();
  const referer = headersList.get('referer');
  try {
    await connectToDB();

    const prompts = await Prompt.find({}).populate('creator');
    return new Response(JSON.stringify(prompts), {
      status: 200,
      headers: {
        referer: referer,
        'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate',
      },
    });
  } catch (error) {
    return new Response('Failed to fetch all prompts', { status: 500 });
  }
};
```
The first clue I found was looking into the deployment's runtime logs and noticing how `api/prompt` response was giving a status code of 304 status code meaning Not Modified. Looking into it a bit more it's apparently because of Vercel does caching which differs from the local environment (and explains why on localhost it works fine). After editing the code the `api/prompt` log gives the 200 status code and says 'MongoBD connect'.

Another thing I noted was how before, the `api/prompt` was in the ISR Functions section of the deployment summary but afterwards it's in the Functions section. It's something about changing it from a static route handler to a dynamic route handler.

I skimmed through these links to get some sort of idea to a solution:

- https://stackoverflow.com/questions/73390663/next-app-deployed-on-vercel-request-for-new-refresh-token-leads-to-unwanted-304
- https://github.com/vercel/next.js/discussions/39855#discussioncomment-5874201
- https://nextjs.org/docs/app/building-your-application/routing/router-handlers#headers

**Comment by zzh315** [comment]
> I've been having the same issue but I managed to get it to work somehow, though I won't be able to why exactly it works since I'm in the same boat of just learning how to use Next.js through this tutorial (so if someone would be able to do that or improve/explain the code below I'd greatly appreciate it!).
> 
> I edited the `/app/api/prompt/route.js` to be this:
> 
> ```
> import Prompt from '@models/prompt';
> import { connectToDB } from '@utils/database';
> import { headers } from 'next/headers';
> 
> export const GET = async (request) => {
>   const headersList = headers();
>   const referer = headersList.get('referer');
>   try {
>     await connectToDB();
> 
>     const prompts = await Prompt.find({}).populate('creator');
>     return new Response(JSON.stringify(prompts), {
>       status: 200,
>       headers: {
>         referer: referer,
>         'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate',
>       },
>     });
>   } catch (error) {
>     return new Response('Failed to fetch all prompts', { status: 500 });
>   }
> };
> ```
> 
> The first clue I found was looking into the deployment's runtime logs and noticing how `api/prompt` response was giving a status code of 304 status code meaning Not Modified. Looking into it a bit more it's apparently because of Vercel does caching which differs from the local environment (and explains why on localhost it works fine). After editing the code the `api/prompt` log gives the 200 status code and says 'MongoBD connect'.
> 
> Another thing I noted was how before, the `api/prompt` was in the ISR Functions section of the deployment summary but afterwards it's in the Functions section. It's something about changing it from a static route handler to a dynamic route handler.
> 
> I skimmed through these links to get some sort of idea to a solution:
> 
> * https://stackoverflow.com/questions/73390663/next-app-deployed-on-vercel-request-for-new-refresh-token-leads-to-unwanted-304
> * [Is server code executed with 304 vercel/next.js#39855 (comment)](https://github.com/vercel/next.js/discussions/39855#discussioncomment-5874201)
> * https://nextjs.org/docs/app/building-your-application/routing/router-handlers#headers

Thanks for the info! What does referer to in this case and can you try removeing it? I googoled and it seems to be optional. Could you try if it will work without importing headers functionlaitys and just add {'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate',} stright into Response. Thanks.

**Comment by 4Furki4** [comment]
It drove me crazy and tried solving it by converting my app/ path (Home Component in the app/page.tsx) to SSR but it was impossible bc we're not fetching, we're connecting to db using Mongoose. 

I tried to request using fetch to our api/prompt/router.ts endpoint but it always throws invalid URL error (it is invalid bc it doesn't convert "/api/prompt" to our router's endpoint in the Home Component for some reason).

Can someone explain why next.js kept giving a response with 304 code when deployed to Vercel (or another site) but didn't cache and give response with 200 when starting the local build ? 

Thank you for the solution, it now works as expected

**Comment by andreshungbz** [comment]
I'd like to add a more succinct solution I had found online for future reference. https://stackoverflow.com/a/76548006

In this case just add `export const revalidate = 0;` to the route. My bandaid solution before seems to also caused an unintended bug where nothing loads on first visit and you have to refresh the page for it to show up.

There may be a few caching shenanigans going on but hopefully this is a cleaner solution for now. In the Next.js documentation: https://nextjs.org/docs/app/building-your-application/data-fetching/caching#segment-level-caching

**Comment by nurhusenm** [comment]
> > I've been having the same issue but I managed to get it to work somehow, though I won't be able to why exactly it works since I'm in the same boat of just learning how to use Next.js through this tutorial (so if someone would be able to do that or improve/explain the code below I'd greatly appreciate it!).
> > I edited the `/app/api/prompt/route.js` to be this:
> > ```
> > import Prompt from '@models/prompt';
> > import { connectToDB } from '@utils/database';
> > import { headers } from 'next/headers';
> > 
> > export const GET = async (request) => {
> >   const headersList = headers();
> >   const referer = headersList.get('referer');
> >   try {
> >     await connectToDB();
> > 
> >     const prompts = await Prompt.find({}).populate('creator');
> >     return new Response(JSON.stringify(prompts), {
> >       status: 200,
> >       headers: {
> >         referer: referer,
> >         'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate',
> >       },
> >     });
> >   } catch (error) {
> >     return new Response('Failed to fetch all prompts', { status: 500 });
> >   }
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The first clue I found was looking into the deployment's runtime logs and noticing how `api/prompt` response was giving a status code of 304 status code meaning Not Modified. Looking into it a bit more it's apparently because of Vercel does caching which differs from the local environment (and explains why on localhost it works fine). After editing the code the `api/prompt` log gives the 200 status code and says 'MongoBD connect'.
> > Another thing I noted was how before, the `api/prompt` was in the ISR Functions section of the deployment summary but afterwards it's in the Functions section. It's something about changing it from a static route handler to a dynamic route handler.
> > I skimmed through these links to get some sort of idea to a solution:
> > 
> > * https://stackoverflow.com/questions/73390663/next-app-deployed-on-vercel-request-for-new-refresh-token-leads-to-unwanted-304
> > * [Is server code executed with 304 vercel/next.js#39855 (comment)](https://github.com/vercel/next.js/discussions/39855#discussioncomment-5874201)
> > * https://nextjs.org/docs/app/building-your-application/routing/router-handlers#headers
> 
> Thanks for the info! What does referer to in this case and can you try removeing it? I googoled and it seems to be optional. Could you try if it will work without importing headers functionlaitys and just add {'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate',} stright into Response. Thanks.



thanks boy,
i used to try different methods like exporting dynamics ... and alot but now this one fixed it and now it fetches every prompt,

alhamdulilah
