### ISSUE TITLE
globals.css error

### ISSUE THREAD

**Issue by aloska** [adrianhajdin/project_next_13_ai_prompt_sharing#4]
./styles/globals.css:75:5
Syntax error: C:\WORK\REACT\NEXTJS\promptopia\styles\globals.css The `sm:` class does not exist. If `sm:` is a custom class, make sure it is defined within a `@layer` directive.

  73 | 
  74 | .app {
> 75 |     @apply relative z-10 flex justify-center items-center flex-col max-w-7xl mx-auto sm: px-16 px-6;
     |     ^
  76 | }
  77 |

**Comment by alirmemon37** [comment]
There's a space between ```sm:``` and  ```px-16```. Remove the space and it should work
```
.app {
  @apply relative z-10 flex justify-center items-center flex-col max-w-7xl mx-auto sm:px-16 px-6;
}
```

**Comment by aloska** [comment]
it works, thanks!
VS Code automatically formating before save 😫
