### ISSUE TITLE
[CLIENT_FETCH_ERROR] after deploying to the web using firebase

### ISSUE THREAD

**Issue by bbkx226** [adrianhajdin/project_next_13_ai_prompt_sharing#40]
Do you know if anyone else has encountered the same issue? The application functions properly on localhost, but after deploying it to the web using Firebase, it fails to work. I have thoroughly reviewed the .env file and everything appears to be correct, yet the application still does not function. 

The NEXTAUTH_URL:
![image](https://github.com/adrianhajdin/project_next_13_ai_prompt_sharing/assets/83408362/f97fa2c1-79a6-405f-b608-08b2d386a4e0)
![image](https://github.com/adrianhajdin/project_next_13_ai_prompt_sharing/assets/83408362/afda8cb8-8e56-45c6-a4fa-30504ccebc27)

The following error message is displayed:
![image](https://github.com/adrianhajdin/project_next_13_ai_prompt_sharing/assets/83408362/f2fc4e78-8f59-4e39-a29b-60c3718f0198)

**Comment by Derflex-primo** [comment]
same problem. Did you already fix it?

**Comment by bbkx226** [comment]
no problem after I switched to Vercel
