### ISSUE TITLE
'post.creator.image' / 'post.creator.email' is undefined

### ISSUE THREAD

**Issue by sidx04** [adrianhajdin/project_next_13_ai_prompt_sharing#46]
![image](https://github.com/adrianhajdin/project_next_13_ai_prompt_sharing/assets/81173756/eb49156e-1307-456f-9c5b-62b83c70a7b1)
Error seems to appear from this block of code for the image attribute.
```javascript
         <Image
            src={post.creator.image}
            alt="user_image"
            width={40}
            height={40}
            className="rounded-full object-contain"
          />
```
This is probably a client-side error, as the back-end throws no error. 
![image](https://github.com/adrianhajdin/project_next_13_ai_prompt_sharing/assets/81173756/456213ce-b94e-428d-a4ad-9af7fe369b8d)

Any fixes? Or this is an issue bug?

**Comment by ryanmoehs** [comment]
same here. but my error is in `creator`. The message is
`TypeError: Cannot read properties of undefined (reading 'creator')`

**Comment by sidx04** [comment]
> same here. but my error is in `creator`. The message is `TypeError: Cannot read properties of undefined (reading 'creator')`

@ryanmoehs guessing you're on windows?

**Comment by Nerih** [comment]
Hi, i traced this issue, to the creator not being in the prompt's. You can see this in your DB, under the prompts table, you will not see any user info in the prompt itself.
To make this more robust, i suggest you add required to the creator fielld in the  Prompt model (Prompt.js).
Then when you restart your project, you and try to add a new prompt, you will see that there is infact no user/creator being passed.

This is most likely because the async function, session, in your auth - route.js is not in the callbacks : make sure your call backs has this:

`const handler = NextAuth({
    providers: [
        GoogleProvider({
            clientId: process.env.GOOGLE_ID,
            clientSecret: process.env.GOOGLE_CLIENT_SECRET
        })
    ],
    callbacks: {
        async session({session}) {
            const sessionUser = await User.findOne({
                email: session.user.email
            })
            console.log("logging session user")
            console.log(sessionUser._id.toString())
            session.user.id = sessionUser._id.toString();
        },
        async signIn({profile}){
            try{
                await connectToDatabase();
    
                // check if user exists
                const userExists = await User.findOne({
                    email: profile.email
                });
                // if not, create user
                if(!userExists){
                    await User.create({
                        email: profile.email,
                        username: profile.name.replace(" ","").toLowerCase(),
                        image: profile.picture
                    })
                }
    
                return true;
    
            } catch (error) {
                console.log(error);
                return false;
            }
        }
    }

})`

**Comment by Nerih** [comment]
ok, so i solved this issue - i ended up taking the route.js for the auth from github and pasting that in to my code, as i noticed i had not moved all my async functions into the call back, as per the video.

then, i added required to the creater field in the prompt.js

then, i checked Mongo to see if i had any prompts that didn't have a userid object - and non of them did, so i had to delete them all. 

then i recreated some prompts, and made sure the user object was in each prompt. Then, i reran the feed code, and it worked fine.

Hope this helps.

**Comment by ryanmoehs** [comment]
> > same here. but my error is in `creator`. The message is `TypeError: Cannot read properties of undefined (reading 'creator')`
> 
> @ryanmoehs guessing you're on windows?

yes

**Comment by ryanmoehs** [comment]
> ok, so i solved this issue; the problem happens if the creator/user information is not stored in the prompt in the DB, this happened to me due to a code error in my auth, which skipped populating session.user.id.
> 
> i ended up taking the route.js for the auth from github and pasting that in to my code, as i noticed i had not moved all my async functions into the call back, as per the video.
> 
> then, i added required to the creater field in the prompt.js
> 
> then, i checked Mongo to see if i had any prompts that didn't have a userid object - and non of them did, so i had to delete them all.
> 
> then i recreated some prompts, and made sure the user object was in each prompt. Then, i reran the feed code, and it worked fine.
> 
> Hope this helps.

What code do you add to `the creator field`? i've been copied code from creator's repo and still don't work.
and this one ..
> then, i checked Mongo to see if i had any prompts that didn't have a userid object - and non of them did, so i had to delete them all.
in my mongo, id is exist (in my mongo written as `_id`). so.., how can I do?

**Comment by Nerih** [comment]
have you checked your MongoDb to makesure that the creator field 

> > ok, so i solved this issue; the problem happens if the creator/user information is not stored in the prompt in the DB, this happened to me due to a code error in my auth, which skipped populating session.user.id.
> > i ended up taking the route.js for the auth from github and pasting that in to my code, as i noticed i had not moved all my async functions into the call back, as per the video.
> > then, i added required to the creater field in the prompt.js
> > then, i checked Mongo to see if i had any prompts that didn't have a userid object - and non of them did, so i had to delete them all.
> > then i recreated some prompts, and made sure the user object was in each prompt. Then, i reran the feed code, and it worked fine.
> > Hope this helps.
> 
> What code do you add to `the creator field`? i've been copied code from creator's repo and still don't work. and this one ..
> 
> > then, i checked Mongo to see if i had any prompts that didn't have a userid object - and non of them did, so i had to delete them all.
> > in my mongo, id is exist (in my mongo written as `_id`). so.., how can I do?

In MongoDB: 
![Screenshot 2023-07-19 193135](https://github.com/adrianhajdin/project_next_13_ai_prompt_sharing/assets/34948835/41e0db0d-10df-4eb5-99a6-ac04fdb9d4b6)
please make sure the creator entry is populated for every item in your prompts namespace.

**Comment by Nerih** [comment]
you can browse my files: https://github.com/Nerih/share_prompts
i've not completed the tutorial yet - so you will see changes happening as i commit.

**Comment by ryanmoehs** [comment]
Finally.. after I discuss with my friend (@hanifanazka), we can just add
```js
const promptCards = posts.map(post =>
    <PromptCard post={post} handleTagClick={() => {}} /> 
  );`
in Feed.jsx before return and put `{promptCards}` in to the return. So the Feed.jsx is become : 
```js
...
const Feed = () => {
  const [searchText, setSearchText] = useState("");
  const [posts, setPosts] = useState([]); // update state
  const handleSearchChange = (e) => {

  };

  useEffect(() => {
    const fetchPosts = async () => {
      const response = await fetch("api/prompt");
      const data = await response.json();
      console.log(data)
      setPosts(data);
    };
    fetchPosts();
  }, []);

  // transform from array to object
  const promptCards = posts.map(post =>
    <PromptCard post={post} handleTagClick={() => {}} /> 
  );
  return (
    <section className="feed">
      <form className="relative w-full flex-center">
        <input className="search_input peer" type="text" placeholder="Search for a tag or username" value={searchText} onChange={handleSearchChange} required />
      </form>

      <PromptCardList 
        data={posts}
        handleTagClick={()=>{}}
      />
      {/* show prompts */}
      {promptCards}
    </section>
  );
};
...
```

**Comment by sidx04** [comment]
@ryanmoehs @Nerih thank you for discussing, i went through both of your solutions and both of them work. closing the issue now :))
