### ISSUE TITLE
Atlas Error Sign in Error Access Denied MongoDb [SOLVED]

### ISSUE THREAD

**Issue by RobItu** [adrianhajdin/project_next_13_ai_prompt_sharing#52]
So I've noticed there have been a lot of issues regarding the Mongoose Database not storing the share_prompt (users) collection. In the `route.js` file, changing `callbacks` to `callback` does **NOT** work, as the NextJS will just skip over this section and not allow MongoDB to save the collection. Here's my solution that worked for me:

## STEP 1 - Add admin privileges to your user in the MongoDB ATLAS
- Go to `Database Access` section of the MongoDB ATLAS, click on EDIT on **the user that is in your MONGODB_URI in your .env file**
- Under the `Built-in Role` select the `Atlas admin` option and Update User to confirm changes.

![1](https://github.com/adrianhajdin/project_next_13_ai_prompt_sharing/assets/74835755/66e0252a-ed78-4d4e-a097-7c64ace05f75)

![2](https://github.com/adrianhajdin/project_next_13_ai_prompt_sharing/assets/74835755/f593bcf7-7271-4e93-b76a-95a865e0f176)

## STEP 2 - Change route.js signIn arguements
- Go to `route.js` and find `async signIn( { profile } ){ ... }`
- Change it to `async signIn({ account, profile, user, credentials }) { ... }` as shown in the picture. You can also find the copy the entire route.js file from [my Repo](https://github.com/RobItu/Promptopia/blob/main/app/api/auth/%5B...nextauth%5D/route.js)

![3](https://github.com/adrianhajdin/project_next_13_ai_prompt_sharing/assets/74835755/88f25cf6-e27c-4259-988d-c06b18c454f8)

## Additional Notes
If this doesn't work make sure that your **MONGODB_URI** variable in your .env file is properly populated with the correct username **AND** password. 

Credit to [Effam](https://github.com/Effham) for finding the Step 2 of this solution here: #47

**Comment by SaurabhHorizon** [comment]
this did not work for me it's still not connecting

**Comment by SaurabhHorizon** [comment]
[next-auth][warn][NO_SECRET] 
https://next-auth.js.org/warnings#no_secret

i get this on the terminal!

**Comment by SaurabhHorizon** [comment]
message: 'decryption operation failed',
  stack: 'JWEDecryptionFailed: decryption operation failed\n' +
    '    at gcmDecrypt (webpack-internal:///(sc_server)/./node_modules/jose/dist/node/esm/runtime/decrypt.js:81:15)\n' +
    '    at decrypt (webpack-internal:///(sc_server)/./node_modules/jose/dist/node/esm/runtime/decrypt.js:104:20)\n' +
    '    at flattenedDecrypt (webpack-internal:///(sc_server)/./node_modules/jose/dist/node/esm/jwe/flattened/decrypt.js:127:90)\n' +
    '    at async compactDecrypt (webpack-internal:///(sc_server)/./node_modules/jose/dist/node/esm/jwe/compact/decrypt.js:22:23)\n' +
    '    at async jwtDecrypt (webpack-internal:///(sc_server)/./node_modules/jose/dist/node/esm/jwt/decrypt.js:12:23)\n' +
    '    at async Object.decode (webpack-internal:///(sc_server)/./node_modules/next-auth/jwt/index.js:44:26)\n' +
    '    at async Object.session (webpack-internal:///(sc_server)/./node_modules/next-auth/core/routes/session.js:25:34)\n' +
    '    at async AuthHandler (webpack-internal:///(sc_server)/./node_modules/next-auth/core/index.js:161:37)\n' +
    '    at async NextAuthRouteHandler (webpack-internal:///(sc_server)/./node_modules/next-auth/next/index.js:49:30)\n' +
    '    at async NextAuth._args$ (webpack-internal:///(sc_server)/./node_modules/next-auth/next/index.js:83:24)\n' +
    '    at async eval (webpack-internal:///(sc_server)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:244:37)',
  name: 'JWEDecryptionFailed'
}

**Comment by RobItu** [comment]
`MongoServerError: bad auth: authentication failed` check your credentials maybe?

**Comment by akinyedetomiwa** [comment]
@RobItu anytime i try to sign in i keep getting this error message in my terminal. can you help  please
Error checking if user exists: User validation failed: Username.username: Username is required!
- info Loaded env from C:\Users\USER PC\Desktop\prompty\.env
- wait compiling...
- event compiled client and server successfully in 558 ms (781 modules)
MongoDB connected
Error checking if user exists: User validation failed: Username.username: Username is required!

![Screenshot 2023-07-26 113902](https://github.com/adrianhajdin/project_next_13_ai_prompt_sharing/assets/126210221/dbd2f838-63be-437d-b1c6-20e8d4c23cea)

**Comment by RobItu** [comment]
Sounds like a *MONGODB_URI* problem. Check that you inputted your username in <username> there as well.

**Comment by akinyedetomiwa** [comment]
Thank you so much @RobItu i have fixed it

**Comment by Ashwinth04** [comment]
> Thank you so much @RobItu i have fixed it

I am also getting the same error. Can you please tell me how you fixed it?

**Comment by divyanshucode** [comment]
> when i changed callback to callbacks the terminal shows
> 
> MongoDB connected [next-auth][error][JWT_SESSION_ERROR] https://next-auth.js.org/errors#jwt_session_error Operation `users.findOne()` buffering timed out after 10000ms { message: 'Operation `users.findOne()` buffering timed out after 10000ms', stack: 'MongooseError: Operation `users.findOne()` buffering timed out after 10000ms\n' + ' at Timeout. (C:\promt\promt\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:185:23)\n' + ' at listOnTimeout (node:internal/timers:569:17)\n' + ' at process.processTimers (node:internal/timers:512:7)', name: 'MongooseError' }
> 
> * error unhandledRejection: Error [MongoServerError]: bad auth : authentication failed
>   at Connection.onMessage (C:\promt\promt\node_modules\mongodb\lib\cmap\connection.js:202:26)
>   at MessageStream. (C:\promt\promt\node_modules\mongodb\lib\cmap\connection.js:61:60)
>   at MessageStream.emit (node:events:513:28)
>   at processIncomingData (C:\promt\promt\node_modules\mongodb\lib\cmap\message_stream.js:124:16)
>   at MessageStream._write (C:\promt\promt\node_modules\mongodb\lib\cmap\message_stream.js:33:9)
>   at writeOrBuffer (node:internal/streams/writable:392:12)
>   at _write (node:internal/streams/writable:333:10)
>   at Writable.write (node:internal/streams/writable:337:10)
>   at TLSSocket.ondata (node:internal/streams/readable:766:22)
>   at TLSSocket.emit (node:events:513:28)
>   at addChunk (node:internal/streams/readable:324:12)
>   at readableAddChunk (node:internal/streams/readable:297:9)
>   at Readable.push (node:internal/streams/readable:234:10)
>   at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
>   at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
>   digest: undefined
>   }
>   MongooseError: Operation `users.findOne()` buffering timed out after 10000ms
>   at Timeout. (C:\promt\promt\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:185:23)
>   at listOnTimeout (node:internal/timers:569:17)
>   at process.processTimers (node:internal/timers:512:7)

hi saurabh iam getting same error how did you solved it

**Comment by RobItu** [comment]
> > * error unhandledRejection: Error [MongoServerError]: bad auth : authentication failed

Check your username and password are correctly written in your env file
