### ISSUE TITLE
Access blocked: This app’s request is invalid

### ISSUE THREAD

**Issue by vaasanthk** [adrianhajdin/project_next_13_ai_prompt_sharing#7]
I cannot pass the authentication sign in page. It shows localhost 300 instead of 3000. When I click on error details I have attached the snapshot. If I  add 300 then it works but not with 3000. How do I resolve this ?

![Screenshot from 2023-05-13 21-23-43](https://github.com/adrianhajdin/project_next_13_ai_prompt_sharing/assets/41782835/b4e4edfa-10b4-46c0-89f7-e954e692b97b)
![Screenshot from 2023-05-13 21-16-33](https://github.com/adrianhajdin/project_next_13_ai_prompt_sharing/assets/41782835/29d54ab7-1e8b-49cb-827c-cfe430103ea9)

**Comment by vaasanthk** [comment]
I figured it out the mistake was in NEXTAUTH_URL in my env file.

**Comment by kirizarry47** [comment]
how did you fix this error?
