### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'image')

### ISSUE THREAD

**Issue by aipni** [adrianhajdin/project_next_13_ai_prompt_sharing#93]
from console chrome dev tools
"
TypeError: Cannot read properties of null (reading 'image')
    at o (page-241b7b2b063c19b3.js:1:1965)
 "
   
from console chrome dev tools
"
"div", {
                        className: "flex-1 flex justify-start items-center gap-3 cursor-pointer",
                        onClick: f,
                        children: [(0,
                        r.jsx)(n(), {
                            **src: t.creator.image,**
                            alt: "user_image",
                            width: 40,
                            height: 40,
                            className: "rounded-full object-contain"
                        }),                 
"

webpage home after deploying to vercel
    "
    Application error: a client-side exception has occurred (see the browser console for more information).
"

**Comment by aipni** [comment]
![error-web2](https://github.com/adrianhajdin/project_next_14_ai_prompt_sharing/assets/46469296/ff2ead4d-507e-45d1-9282-d1b611779ca9)
![error-web](https://github.com/adrianhajdin/project_next_14_ai_prompt_sharing/assets/46469296/e31847f5-10df-45a9-88c7-cd184e8964fe)

**Comment by aipni** [comment]
Can anyone help on this issue

**Comment by aipni** [comment]
on my local development i got an error on this part

"
 **<**Image
            src={post.creator.image}
            alt='user_image'
            width={40}
            height={40}
            className='rounded-full object-contain'**
          />**
"
![Unhandled Runtime Error](https://github.com/adrianhajdin/project_next_14_ai_prompt_sharing/assets/46469296/edcd71e0-14ae-40af-9d76-5403396935e9)

**Comment by aipni** [comment]
return (    **_**post && post.creator &&**_**
***
***
***
);


Adding above bold code fixed the issue

**Comment by giriyaram** [comment]
could you please specify, where to add this code "return ( post && post.creator &&"

**Comment by aipni** [comment]
components/PromptCard.jsx

line number 29
